import Img1 from './assets/img/City_6.jpg';
import Img2 from './assets/img/City_33.jpg';
import Img3 from './assets/img/City_44.jpg';
import Img4 from './assets/img/City_99.jpg';
import Img5 from './assets/img/City_138.jpg';

export const imgLoop = [Img1, Img2, Img3, Img4, Img5];

const apiData = [
	{
		id: Math.random(),
		title: '3 Bedrooms Self Contained',
		desc: 'My description about this very nice listing that am putting my place up for rent. This will be the very first or second time i list my place out for people to use.',
		location: 'Adenta, Accra',
		price: 4000,
		typeOfListing: 'Apartment',
		amenities: ['Pool', 'Parking space', 'Wifi', 'BBQ'],
		imgUrl: Img1,
		host: {
			name: 'Host 1',
			location: 'Adenta',
			phoneNum: '0123456789',
			email: 'host1@roomzy.com',
			isVerified: false,
		},
		reviews: [
			{
				id: 1124,
				user: 'User 1',
				review: 'My first review',
				rating: 3,
			},
		],
		minPrice: 3500,
		maxPrice: 4000,
	},
	{
		id: Math.random(),
		title: 'Office Space',
		desc: 'My description about this very nice listing that am putting my place up for rent. This will be the very first or second time i list my place out for people to use.',
		location: 'Kasoa, Accra',
		price: 1000,
		typeOfListing: 'House',
		amenities: ['Pool', 'Parking space', 'Wifi', 'BBQ'],
		imgUrl: Img2,
		host: {
			name: 'Host 2',
			location: 'Madina',
			phoneNum: '0123456789',
			email: 'host2@roomzy.com',
			isVerified: true,
		},
		reviews: [
			{
				id: 1124,
				user: 'User 4',
				review: 'Great experience',
				rating: 5,
			},
		],
		minPrice: 3500,
		maxPrice: 4000,
	},
	{
		id: Math.random(),
		title: 'Single Room',
		desc: 'My description about this very nice listing that am putting my place up for rent. This will be the very first or second time i list my place out for people to use.',
		location: 'Cape Coast, Central',
		price: 1000,
		typeOfListing: 'House',
		amenities: ['Pool', 'Parking space', 'Wifi', 'BBQ'],
		imgUrl: Img3,
		host: {
			name: 'Host 2',
			location: 'Madina',
			phoneNum: '0123456789',
			email: 'host2@roomzy.com',
			isVerified: true,
		},
		reviews: [
			{
				id: 1124,
				user: 'User 4',
				review: 'Great experience',
				rating: 5,
			},
		],
		minPrice: 3500,
		maxPrice: 4000,
	},
	{
		id: Math.random(),
		title: '2 Bedrooms Self Contained',
		desc: 'My description about this very nice listing that am putting my place up for rent. This will be the very first or second time i list my place out for people to use.',
		location: 'Madina, Accra',
		price: 1000,
		typeOfListing: 'House',
		amenities: ['Pool', 'Parking space', 'Wifi', 'BBQ'],
		imgUrl: Img2,
		host: {
			name: 'Host 2',
			location: 'Madina',
			phoneNum: '0123456789',
			email: 'host2@roomzy.com',
			isVerified: true,
		},
		reviews: [
			{
				id: 1124,
				user: 'User 4',
				review: 'Great experience',
				rating: 5,
			},
		],
		minPrice: 3500,
		maxPrice: 4000,
	},
	{
		id: Math.random(),
		title: '2 Bedrooms Self Contained',
		desc: 'My description about this very nice listing that am putting my place up for rent. This will be the very first or second time i list my place out for people to use.',
		location: 'Madina, Accra',
		price: 1000,
		typeOfListing: 'House',
		amenities: ['Pool', 'Parking space', 'Wifi', 'BBQ'],
		imgUrl: Img4,
		host: {
			name: 'Host 2',
			location: 'Madina',
			phoneNum: '0123456789',
			email: 'host2@roomzy.com',
			isVerified: true,
		},
		reviews: [
			{
				id: 1124,
				user: 'User 4',
				review: 'Great experience',
				rating: 5,
			},
		],
		minPrice: 3500,
		maxPrice: 4000,
	},
	{
		id: Math.random(),
		title: '2 Bedrooms Self Contained',
		desc: 'My description about this very nice listing that am putting my place up for rent. This will be the very first or second time i list my place out for people to use.',
		location: 'Madina, Accra',
		price: 1000,
		typeOfListing: 'House',
		amenities: ['Pool', 'Parking space', 'Wifi', 'BBQ'],
		imgUrl: Img1,
		host: {
			name: 'Host 2',
			location: 'Madina',
			phoneNum: '0123456789',
			email: 'host2@roomzy.com',
			isVerified: true,
		},
		reviews: [
			{
				id: 1124,
				user: 'User 4',
				review: 'Great experience',
				rating: 5,
			},
		],
		minPrice: 3500,
		maxPrice: 4000,
	},
	{
		id: Math.random(),
		title: '2 Bedrooms Self Contained',
		desc: 'My description about this very nice listing that am putting my place up for rent. This will be the very first or second time i list my place out for people to use.',
		location: 'Madina, Accra',
		price: 1000,
		typeOfListing: 'House',
		amenities: ['Pool', 'Parking space', 'Wifi', 'BBQ'],
		imgUrl: Img5,
		host: {
			name: 'Host 2',
			location: 'Madina',
			phoneNum: '0123456789',
			email: 'host2@roomzy.com',
			isVerified: true,
		},
		reviews: [
			{
				id: 1124,
				user: 'User 4',
				review: 'Great experience',
				rating: 5,
			},
		],
		minPrice: 3500,
		maxPrice: 4000,
	},
	{
		id: Math.random(),
		title: '2 Bedrooms Self Contained',
		desc: 'My description about this very nice listing that am putting my place up for rent. This will be the very first or second time i list my place out for people to use.',
		location: 'Madina, Accra',
		price: 1000,
		typeOfListing: 'House',
		amenities: ['Pool', 'Parking space', 'Wifi', 'BBQ'],
		imgUrl: Img3,
		host: {
			name: 'Host 2',
			location: 'Madina',
			phoneNum: '0123456789',
			email: 'host2@roomzy.com',
			isVerified: true,
		},
		reviews: [
			{
				id: 1124,
				user: 'User 4',
				review: 'Great experience',
				rating: 5,
			},
		],
		minPrice: 3500,
		maxPrice: 4000,
	},
	{
		id: Math.random(),
		title: '2 Bedrooms Self Contained',
		desc: 'My description about this very nice listing that am putting my place up for rent. This will be the very first or second time i list my place out for people to use.',
		location: 'Madina, Accra',
		price: 1000,
		typeOfListing: 'House',
		amenities: ['Pool', 'Parking space', 'Wifi', 'BBQ'],
		imgUrl: Img2,
		host: {
			name: 'Host 2',
			location: 'Madina',
			phoneNum: '0123456789',
			email: 'host2@roomzy.com',
			isVerified: true,
		},
		reviews: [
			{
				id: 1124,
				user: 'User 4',
				review: 'Great experience',
				rating: 5,
			},
		],
		minPrice: 3500,
		maxPrice: 4000,
	},
	{
		id: Math.random(),
		title: 'Office Space',
		desc: 'My description about this very nice listing that am putting my place up for rent. This will be the very first or second time i list my place out for people to use.',
		location: 'Madina, Accra',
		price: 1000,
		typeOfListing: 'Office',
		amenities: ['Pool', 'Parking space', 'Wifi', 'BBQ'],
		imgUrl: Img5,
		host: {
			name: 'Host 2',
			location: 'Madina',
			phoneNum: '0123456789',
			email: 'host2@roomzy.com',
			isVerified: true,
		},
		reviews: [
			{
				id: 1124,
				user: 'User 4',
				review: 'Great experience',
				rating: 5,
			},
		],
		minPrice: 3500,
		maxPrice: 4000,
	},
	{
		id: Math.random(),
		title: '2 Bedrooms Apartment',
		desc: 'My description about this very nice listing that am putting my place up for rent. This will be the very first or second time i list my place out for people to use.',
		location: 'Madina, Accra',
		price: 1000,
		typeOfListing: 'Apartment',
		amenities: ['Pool', 'Parking space', 'Wifi', 'BBQ'],
		imgUrl: Img4,
		host: {
			name: 'Host 2',
			location: 'Madina',
			phoneNum: '0123456789',
			email: 'host2@roomzy.com',
			isVerified: true,
		},
		reviews: [
			{
				id: 1124,
				user: 'User 4',
				review: 'Great experience',
				rating: 5,
			},
		],
		minPrice: 3500,
		maxPrice: 4000,
	},
];

export default apiData;
