const apiData = [
	{
		id: Math.random(),
		title: '3 Bedrooms Self Contained',
		desc: 'My description about this very nice listing that am putting my place up for rent. This will be the very first or second time i list my place out for people to use.',
		location: 'Adenta, Accra',
		price: 4000,
		typeOfListing: 'Apartment',
		amenities: [],
		imgUrl: '',
		host: {
			name: 'Host 1',
			location: 'Adenta',
			phoneNum: '0123456789',
			email: 'host1@roomzy.com',
			isVerified: false,
		},
		reviews: [
			{
				id: 1124,
				user: 'User 1',
				review: 'My first review',
				rating: 3,
			},
		],
		minPrice: 3500,
		maxPrice: 4000,
	},
	{
		id: Math.random(),
		title: 'Office Space',
		desc: 'My description about this very nice listing that am putting my place up for rent. This will be the very first or second time i list my place out for people to use.',
		location: 'Kasoa, Accra',
		price: 1000,
		typeOfListing: 'House',
		amenities: [],
		imgUrl: '',
		host: {
			name: 'Host 2',
			location: 'Madina',
			phoneNum: '0123456789',
			email: 'host2@roomzy.com',
			isVerified: true,
		},
		reviews: [
			{
				id: 1124,
				user: 'User 4',
				review: 'Great experience',
				rating: 5,
			},
		],
		minPrice: 3500,
		maxPrice: 4000,
	},
	{
		id: Math.random(),
		title: 'Single Room',
		desc: 'My description about this very nice listing that am putting my place up for rent. This will be the very first or second time i list my place out for people to use.',
		location: 'Cape Coast, Central',
		price: 1000,
		typeOfListing: 'House',
		amenities: [],
		imgUrl: '',
		host: {
			name: 'Host 2',
			location: 'Madina',
			phoneNum: '0123456789',
			email: 'host2@roomzy.com',
			isVerified: true,
		},
		reviews: [
			{
				id: 1124,
				user: 'User 4',
				review: 'Great experience',
				rating: 5,
			},
		],
		minPrice: 3500,
		maxPrice: 4000,
	},
	{
		id: Math.random(),
		title: '2 Bedrooms Self Contained',
		desc: 'My description about this very nice listing that am putting my place up for rent. This will be the very first or second time i list my place out for people to use.',
		location: 'Madina, Accra',
		price: 1000,
		typeOfListing: 'House',
		amenities: [],
		imgUrl: '',
		host: {
			name: 'Host 2',
			location: 'Madina',
			phoneNum: '0123456789',
			email: 'host2@roomzy.com',
			isVerified: true,
		},
		reviews: [
			{
				id: 1124,
				user: 'User 4',
				review: 'Great experience',
				rating: 5,
			},
		],
		minPrice: 3500,
		maxPrice: 4000,
	},
	{
		id: Math.random(),
		title: '2 Bedrooms Self Contained',
		desc: 'My description about this very nice listing that am putting my place up for rent. This will be the very first or second time i list my place out for people to use.',
		location: 'Madina, Accra',
		price: 1000,
		typeOfListing: 'House',
		amenities: [],
		imgUrl: '',
		host: {
			name: 'Host 2',
			location: 'Madina',
			phoneNum: '0123456789',
			email: 'host2@roomzy.com',
			isVerified: true,
		},
		reviews: [
			{
				id: 1124,
				user: 'User 4',
				review: 'Great experience',
				rating: 5,
			},
		],
		minPrice: 3500,
		maxPrice: 4000,
	},
	{
		id: Math.random(),
		title: '2 Bedrooms Self Contained',
		desc: 'My description about this very nice listing that am putting my place up for rent. This will be the very first or second time i list my place out for people to use.',
		location: 'Madina, Accra',
		price: 1000,
		typeOfListing: 'House',
		amenities: [],
		imgUrl: '',
		host: {
			name: 'Host 2',
			location: 'Madina',
			phoneNum: '0123456789',
			email: 'host2@roomzy.com',
			isVerified: true,
		},
		reviews: [
			{
				id: 1124,
				user: 'User 4',
				review: 'Great experience',
				rating: 5,
			},
		],
		minPrice: 3500,
		maxPrice: 4000,
	},
	{
		id: Math.random(),
		title: '2 Bedrooms Self Contained',
		desc: 'My description about this very nice listing that am putting my place up for rent. This will be the very first or second time i list my place out for people to use.',
		location: 'Madina, Accra',
		price: 1000,
		typeOfListing: 'House',
		amenities: [],
		imgUrl: '',
		host: {
			name: 'Host 2',
			location: 'Madina',
			phoneNum: '0123456789',
			email: 'host2@roomzy.com',
			isVerified: true,
		},
		reviews: [
			{
				id: 1124,
				user: 'User 4',
				review: 'Great experience',
				rating: 5,
			},
		],
		minPrice: 3500,
		maxPrice: 4000,
	},
	{
		id: Math.random(),
		title: '2 Bedrooms Self Contained',
		desc: 'My description about this very nice listing that am putting my place up for rent. This will be the very first or second time i list my place out for people to use.',
		location: 'Madina, Accra',
		price: 1000,
		typeOfListing: 'House',
		amenities: [],
		imgUrl: '',
		host: {
			name: 'Host 2',
			location: 'Madina',
			phoneNum: '0123456789',
			email: 'host2@roomzy.com',
			isVerified: true,
		},
		reviews: [
			{
				id: 1124,
				user: 'User 4',
				review: 'Great experience',
				rating: 5,
			},
		],
		minPrice: 3500,
		maxPrice: 4000,
	},
	{
		id: Math.random(),
		title: '2 Bedrooms Self Contained',
		desc: 'My description about this very nice listing that am putting my place up for rent. This will be the very first or second time i list my place out for people to use.',
		location: 'Madina, Accra',
		price: 1000,
		typeOfListing: 'House',
		amenities: [],
		imgUrl: '',
		host: {
			name: 'Host 2',
			location: 'Madina',
			phoneNum: '0123456789',
			email: 'host2@roomzy.com',
			isVerified: true,
		},
		reviews: [
			{
				id: 1124,
				user: 'User 4',
				review: 'Great experience',
				rating: 5,
			},
		],
		minPrice: 3500,
		maxPrice: 4000,
	},
	{
		id: Math.random(),
		title: 'Office Space',
		desc: 'My description about this very nice listing that am putting my place up for rent. This will be the very first or second time i list my place out for people to use.',
		location: 'Madina, Accra',
		price: 1000,
		typeOfListing: 'Office',
		amenities: [],
		imgUrl: '',
		host: {
			name: 'Host 2',
			location: 'Madina',
			phoneNum: '0123456789',
			email: 'host2@roomzy.com',
			isVerified: true,
		},
		reviews: [
			{
				id: 1124,
				user: 'User 4',
				review: 'Great experience',
				rating: 5,
			},
		],
		minPrice: 3500,
		maxPrice: 4000,
	},
	{
		id: Math.random(),
		title: '2 Bedrooms Apartment',
		desc: 'My description about this very nice listing that am putting my place up for rent. This will be the very first or second time i list my place out for people to use.',
		location: 'Madina, Accra',
		price: 1000,
		typeOfListing: 'Apartment',
		amenities: [],
		imgUrl: '',
		host: {
			name: 'Host 2',
			location: 'Madina',
			phoneNum: '0123456789',
			email: 'host2@roomzy.com',
			isVerified: true,
		},
		reviews: [
			{
				id: 1124,
				user: 'User 4',
				review: 'Great experience',
				rating: 5,
			},
		],
		minPrice: 3500,
		maxPrice: 4000,
	},
];

export default apiData;
